machine:
  environment:
    CIRCLE_BUILD_DIR: $HOME/aws-vue
    PATH: $PATH:CIRCLE_BUILD_DIR/bin:${HOME}/aws-vue/node_modules/.bin"

  post:
    - mkdir -p $CIRCLE_BUILD_DIR/bin
  node:
    version: 8.9.1

dependencies:
  pre:
    - go get -v github.com/bep/s3deploy
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
    - bin

test:
  override
    - yarn run build

deployment:
  s3up:
    branch: master
    commands:
      - s3deploy -source=dist/ -region=us-east-2 -bucket=jamiejzhang.com